name: Terraform Deployment with AI QA
on: [push]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello World"
  
  ai-qa-check:
    runs-on: ubuntu-latest
    needs: terraform-apply
    permissions:
      actions: read
      contents: read
    steps:
      - uses: aaryanshroff/ai-terraform-qa-action@v0.0.3
        with:
          tf_apply_job: "terraform-apply"